DROP TABLE IF EXISTS anchor_tx;
DROP TABLE IF EXISTS txout;
DROP TABLE IF EXISTS tx;
DROP TABLE IF EXISTS block;
DROP TABLE IF EXISTS keychain;
DROP TABLE IF EXISTS network;
DROP TABLE IF EXISTS version;