on:
  push:
    branches:
      - master
  pull_request:
env:
  CARGO_TERM_COLOR: always
  POSTGRES_USER: dlcdevkit
  POSTGRES_PASS: dlcdevkit
  DATABASE_URL: postgresql://dlcdevkit:dlcdevkit@localhost:5432/postgres
  BITCOIND_HOST: http://localhost:18443
  BITCOIND_USER: dlcdevkit
  BITCOIND_PASS: dlcdevkit
  ESPLORA_HOST: http://localhost:30000
  RPC_WALLET: ddk

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          components: clippy
          override: true
      - name: Check clippy
        run: cargo clippy -- -D warnings
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Check format
        run: cargo fmt --check
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          override: true
      - name: cargo check
        run: cargo check --all-features
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          components: rustfmt
          override: true
      - name: Start Docker Compose services
        run: docker compose up -d
      - name: Wait for Bitcoin container
        run: |
          chmod +x ./testconfig/scripts/wait_for_container.sh
          ./testconfig/scripts/wait_for_container.sh bitcoin
      - name: Wait for Electrs to be ready
        run: |
          chmod +x ./testconfig/scripts/wait_for_electrs.sh
          ./testconfig/scripts/wait_for_electrs.sh
      - name: Run unit tests
        run: cargo test --all-features
      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v
  integration_tests_prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          components: rustfmt
          override: true
      - uses: actions/cache@v3
        env:
          cache-name: test-cache
        with:
          path: target/debug/deps
          key: test-cache-${{ github.run_id }}-${{ github.run_number }}
      - uses: actions/checkout@v4
      - id: set-matrix
        run: cargo test --no-run --all-features && echo "::set-output name=matrix::$(testconfig/scripts/get_test_list.sh manager_execution manager_tests contract_updater)"
  integration_tests:
    name: integration tests
    needs: integration_tests_prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        tests: ${{ fromJson(needs.integration_tests_prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        env:
          cache-name: test-cache
        with:
          path: target/debug/deps
          key: test-cache-${{ github.run_id }}-${{ github.run_number }}
      - name: Start bitcoin node
        run: docker compose up -d
      - name: Wait for container to run
        run: |
          chmod +x ./testconfig/scripts/wait_for_container.sh
          ./testconfig/scripts/wait_for_container.sh bitcoin
      - name: Wait for electrs to be ready
        run: |
          chmod +x ./testconfig/scripts/wait_for_electrs.sh
          ./testconfig/scripts/wait_for_electrs.sh
      - name: Run test
        run: RUST_BACKTRACE=1 RUST_MIN_STACK=8388608 ${{ matrix.tests }} --ignored
      - name: Stop bitcoin node
        run: docker compose down -v

  test_splicing:
    name: test splicing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Start bitcoin node
        run: docker compose up -d
      - name: Wait for container to run
        run: |
          chmod +x ./testconfig/scripts/wait_for_container.sh
          ./testconfig/scripts/wait_for_container.sh bitcoin
      - name: Wait for electrs to be ready
        run: |
          chmod +x ./testconfig/scripts/wait_for_electrs.sh
          ./testconfig/scripts/wait_for_electrs.sh
      - name: Run test
        run: RUST_MIN_STACK=8388608 cargo test -p ddk-manager splice_test -- --ignored
      - name: Stop bitcoin node
        run: docker compose down -v
